### ISSUE TITLE
Double clicking a tab causes a small white bar to appear

### ISSUE THREAD

**Issue by mbkupfer** [reactjs/react-tabs#300]
A small white bar appears below a tab when it is clicked twice. From my devtools console, it appears to create some type nested element, but it disappears when I try to expand the `<li>` tag. How do I remove, or change the color, of this bar?

Before:
![Screen Shot 2019-07-19 at 1 55 01 PM](https://user-images.githubusercontent.com/6313008/61565112-eba12400-aa2c-11e9-9fec-a73aac5f77f9.png)

After:
(When I try to expand `<li>`, the tab reverts back to the before state.)
![Screen Shot 2019-07-19 at 1 55 07 PM](https://user-images.githubusercontent.com/6313008/61565179-20ad7680-aa2d-11e9-9660-fa7850149177.png)

In addition to the react-tabs styles, I've also added the following overriding styles:

```css
.tabs {
    margin: 24px 20px;
    background-color: #d1d5d7;
    min-height: 88%;
}

.react-tabs__tab-list {
    display: flex;
    justify-content: space-around;
    margin-bottom: 30px;
}

.react-tabs__tab {
    width: calc(100% / 2);
    color: #586069;
    border-top-left-radius: 3px;
    border-top-right-radius: 3px;
    border-top: 3px solid transparent !important;
    border-left: 1px solid #455560 !important;
    border-right: 1px solid #455560 !important;
    border-bottom: 0px !important;
    background-color: #fafbfc;
    padding: 1px !important;
    font-family: arial;
    font-size: 15px;
    font-weight: bold;
    display: flex !important;
    align-items: center;
    justify-content: center;
    line-height: 1.6;
}

.react-tabs__tab--selected {
    color: black;
    border-top: 3px solid rgb(238, 49, 36) !important;
    border-right: 1px solid #455560 !important;
    border-left: 1px solid #455560 !important;
    background-color: #d1d5d7;
}

/* Remove the outside borders of the outside tabs */
.react-tabs__tab:nth-child(1) {
    border-left: 0px !important;
}

.react-tabs__tab:nth-last-child(1) {
    border-right: 0px !important;
}

.react-tabs__tab-panel {
    padding: 0px 10px 20px;
}
```

**Comment by mbkupfer** [comment]
Looking in the react-dev tools console, I actually saw something interesting...it looks like the tab is not focussed which is related to #272.  Perhaps this has something to do with it? I'll try and dig deeper when I have a free chance, but hopefully someone knows of a solution in the meantime.

Much thanks!

Before:

![Screen Shot 2019-07-19 at 2 04 06 PM](https://user-images.githubusercontent.com/6313008/61565536-2a83a980-aa2e-11e9-935f-d9c644db40d5.png)

After: 

![Screen Shot 2019-07-19 at 2 04 17 PM](https://user-images.githubusercontent.com/6313008/61565537-2ce60380-aa2e-11e9-8f53-798af4a18910.png)

**Comment by mbkupfer** [comment]
I was able to figure this out rather quickly. I just needed to overwrite the background color for the following selector:

```css
.react-tabs__tab:focus:after {
    background: <my-new-color>;
}
```

@danez , perhaps this could be improved by programmatically setting this color to match the tab-panel color? That way, no white bar gets created when the tab panel is not white?
